import Footer from "@/components/footer";
import Header from "@/components/header";
import { Providers } from "@/components/providers";
import type { Metadata } from "next";
import { Source_Code_Pro } from "next/font/google";

const sourceCodePro = Source_Code_Pro({
    variable: "--font-source-code-pro",
    subsets: ["latin"],
    weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
    title: "M.Abdelhadi",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${sourceCodePro.variable} antialiased`}>
                <Providers>
                    <Header />
                    <main>
                        {children}
                    </main>
                    <Footer />
                </Providers>
            </body>
        </html >
    );
}
